### ISSUE TITLE
signed/unsigned

### ISSUE THREAD

**Issue by fahim167** [SamuelTulach/mutante#10]
how to fix signed/unsigned in this ??

for (auto i = 0; i < moduleList->ulModuleCount; i++)
	{
		auto module = moduleList->Modules[i];
		if (strstr(module.ImageName, moduleName))
		{
			address = module.Base;
			break;
		}
	}

**Comment by atomik00** [comment]
Replace that section with the code below and that will resolve this issue.
`for (unsigned int i = 0; i < moduleList->ulModuleCount; i++)
	{
		auto module = moduleList->Modules[i];
		if (strstr(module.ImageName, moduleName))
		{
			address = module.Base;
			break;
		}
	}`

**Comment by fahim167** [comment]
really thankful for your reply .. but i tried that and gave me 
MSB4018 The "SignTask" task failed unexpectedly 

the same error when i try to built with x64 not ARM

**Comment by fahim167** [comment]
just ran it as administrator and the error is gone

**Comment by atomik00** [comment]
that error is caused but not having a cert. you can fix it by right clicking on solution and going to properties -> Driver signing -> then making sure its in test sign (Sign mode option should be set to test sign) for Test Certificate Choose Create new. once thats done hit apply and build that error will go away

**Comment by atomik00** [comment]
also dont build as Arm unless you need to, it works fine in x64

**Comment by fahim167** [comment]
now it says 
Could not connect to the remote computer for deployment.
 :(((((((((
