### ISSUE TITLE
Unresolved External Errors on both modes 

### ISSUE THREAD

**Issue by hailzfn** [SamuelTulach/mutante#12]
Debug-LNK2019 unresolved external symbol __stdio_common_vswprintf referenced in function _vsnwprintf_l	mutante	C:\Users\Downloads\mutante-master\mutante-master\mutante\mutante\disks.obj	1	

BuildThis-LNK2019	unresolved external symbol __stdio_common_vswprintf referenced in function "long __cdecl RtlStringCbPrintfW(unsigned short *,unsigned __int64,unsigned short const *,...)" (?RtlStringCbPrintfW@@YAJPEAG_KPEBGZZ)	mutante	C:\Users\Downloads\mutante-master\mutante-master\mutante\mutante\disks.obj	1	

please help I just wanna play cod lmao

**Comment by EugW** [comment]
add -D_NO_CRT_STDIO_INLINE to Compiler command line

**Comment by hailzfn** [comment]
> add -D_NO_CRT_STDIO_INLINE to Compiler command line

Hey man i'm retargeted what do you mean by compiler command line
is it this?
![Screenshot 2021-07-09 173608](https://user-images.githubusercontent.com/76883598/125142040-55181280-e0dc-11eb-9d1f-88b8be6660a9.png)
because that still gives me an unresolved external error sorry if I'm being stupid I deadass want to play cod and can't figure this shit out
if you want you can just send me the file at my discord Hailz#6969
ty for being patient with me

**Comment by EugW** [comment]
> > add -D_NO_CRT_STDIO_INLINE to Compiler command line
> 
> Hey man i'm retargeted what do you mean by compiler command line
> is it this?
> ![Screenshot 2021-07-09 173608](https://user-images.githubusercontent.com/76883598/125142040-55181280-e0dc-11eb-9d1f-88b8be6660a9.png)
> because that still gives me an unresolved external error sorry if I'm being stupid I deadass want to play cod and can't figure this shit out
> if you want you can just send me the file at my discord Hailz#6969
> ty for being patient with me
> 

Yes, it is

**Comment by hailzfn** [comment]
do I need the dash or no

**Comment by EugW** [comment]
> do I need the dash or no
> and it still gives errors regardless :(
> here is debug
> ![debug](https://user-images.githubusercontent.com/76883598/125142437-5b5abe80-e0dd-11eb-8607-d0e2e46bc905.jpg)
> and here is release
> ![REL](https://user-images.githubusercontent.com/76883598/125142456-64e42680-e0dd-11eb-965c-e513b94a4928.jpg)
> 

I sent friend request in discord
