### ISSUE TITLE
SMBIOS STRING RANDOMIZER WRONGLY USED..

### ISSUE THREAD

**Issue by Juesril** [SamuelTulach/mutante#22]
Well as you see in here
![image](https://github.com/SamuelTulach/mutante/assets/45968231/1856f1e9-b2b9-4b06-ab42-0a0297d39480)

After you pass the string, you randomize it, but it will only randomize the variable that holds  the copied string not the real pointer of the string

![image](https://github.com/SamuelTulach/mutante/assets/45968231/c4b9cd2b-a2c1-4d0a-a8e8-2ff44a1ee08b)

You are only retrieving/copying the string value by iterating it, not getting the real address of the string that can be modified, I will provide a solution later if I can.

**Comment by SamuelTulach** [comment]
What you wrote is utter nonsense. Maybe check out [learncpp.com](https://learncpp.com) to figure out how pointers work and what char* (pointer to char) is...
